---
title: "Protocol - Waste Management Lab Course"
subtitle: "WT2023/24 | Course No. 718837"
author: "Thomas Klammsteiner, PhD | Sebastian Hupfauf, PhD"
format: 
  html:
    toc: true
    toc-title: Inhalt
    toc-location: left
    theme: flatly
    page-layout: full
editor: visual
---

<br>

**Course supervisors**:

-   Sebastian Hupfauf, PhD\
    [sebastian.hupfauf\@uibk.ac.at](mailto:sebastian.hupfauf@uibk.ac.at)

-   Thomas Klammsteiner, PhD\
    [thomas.klammsteiner\@uibk.ac.at](mailto:thomas.klammsteiner@uibk.ac.at)

<br>

**Teaching assistant**:

-   Laura M. Marte, BSc\
    [laura.m.marte\@student.uibk.ac.at](mailto:laura.M.Marte@student.uibk.ac.at)

<br>

**Source reference cover picture**:

-   Biogasanlage Jühnde (http://www.goettinger-tageblatt.de)
-   Kuh in den Alpen (https://www.kleinezeitung.at)

**Abbreviations**:

| Abkürzung | Erklärung                                                                   |
|------------------------------------|------------------------------------|
| CNP       | Probennahme für C/N-Analyse                                                 |
| CSB       | Chemischer Sauerstoffbedarf                                                 |
| EC        | elektrische Leitfähigkeit (Electrical Conductivity)                         |
| FOS/TAC   | Alkalinität (Verhältnis von organische Säuren zur Carbonat-Pufferkapazität) |
| GM        | Messung der Gasmenge und Gaszusammensetzung                                 |
| PN/PNF    | Probennahmen / Probennahme und Fütterung                                    |
| PT        | Pathogen Test mit Selektivagar-Platten                                      |
| TS, oTS   | Trockensubstanz, organische Trockensubstanz                                 |
| VFA       | Flüchtige Fettsäuren (Volatile Fatty Acids)                                 |
| DNA Q&S   | DNA-Quantifizierung (Quantus) und Sanger Sequenzierung                      |

**Objective**\
The aim of this lab course is to simulate biogas production on a laboratory scale and to learn methods for measuring important monitoring parameters. This involves adjusting various parameters and observing the effects on gas production and other important process parameters.

**To bring along**\
Lab coat, calculator, writing utensils, permanent marker, this lab protocol, lots of motivation

**Meeting point**\
Mo-Fri, 0900AM, Microbiology - practice laboratory (G02), NATWI building, Technikerstraße 25, 2nd floor!

**Grading**\
The final grade for the lab course is calculated in equal parts (25%) from the following four partial grades:

- **Introduction test**: On the first day of the lab course, there will be a short introductory test on the content of the lab course protocol. The test will largely consist of multiple-choice questions.

- **Collaboration**: The individual co-operation of all students is assessed during the entire internship period.  

- **Group work**:
  - Each group carries out a literature review on their chosen treatment (e.g. co-digestion, temperature, feeding rate) in parallel with their work in the laboratory. The relevance in practice, the effect on the methane yield, the effect on the microorganisms, unanswered questions and the future potential will be discussed. The results will be presented in groups on the last laboratory day using a PC with a projector (approx. 10 minutes per group).
  - The most important results of the biogas monitoring should be presented in groups in the form of posters. On the debriefing date, the posters will be presented to the other course participants and the results presented. In addition, results that were not included in the poster will be presented in a short PowerPoint presentation (duration for poster presentation + presentation of further results: approx. 20 minutes per group). The posters do not have to be printed! The presentations will be made using a PC with a projector.

-   **Abstract**: The students prepare an extended abstract (two A4 pages), as is usual for conference participation or scientific publications. This should explain the experimental approach and present the most important results. Further information on writing a scientific abstract will be provided during the lab course. Ideally, it should be submitted by e-mail (to one of the course instructors), with the day of the debriefing set as the deadline.

**Debriefing with presentations of the posters: 15.01.2024 (14:00-16:00)**\
**The debriefing will take place in the biology seminar room (foyer)**

<br>

# 1. Safety in the lab

## 1.1. Laboratory

Information on the location and use of the laboratory's safety equipment: first aid equipment, escape routes, telephone, fire alarms, location of fire extinguishing agents, eye and emergency showers, absorbent materials for chemicals, main switch for gas and electricity supply.

## 1.2. Behaviour in the lab

- There are no "stupid" questions. If anything is unclear, ask the course instructor or tutor immediately!
- Students must never work alone in the lab.
- When working with unknown chemicals, everyone must be aware of the hazard symbols on the packaging or consult the Internet for information on safe handling (properties, hazard and safety phrases; Material Safety Data Sheet (MSDS)) and possible sources of danger. Example: Use of the GESTIS database!
- Consumption/use and storage of food, drinks, medicines, tobacco products, chewing gum and cosmetics in the laboratory area is prohibited, as is the insertion of contact lenses.
- Work surfaces should always be tidy and clean. The "polluter pays" principle applies: everyone cleans and decontaminates the surfaces, containers, equipment or other facilities they use themselves. Spilt material must be disposed of properly immediately!
- In the evening, windows and tilt windows must be closed, electrical devices switched off and media connections (compressed air, water, deionised water) switched off.
- Hands must be cleaned and disinfected before starting and after completing laboratory work.
- All solutions prepared in the lab, containers used, etc. must be labelled with name (or group number), contents and date without exception. Each student is responsible for the correct disposal of materials. This includes
- Autoclaving enriched bacterial cultures and contaminated laboratory utensils
- Removing the labelling from vessels
- Proper cleaning of containers/laboratory utensils
- Tidying up the containers/chemical packs in their appropriate storage locations

## 1.3. Personal protective equipment

- It is not permitted to work without a lab coat.
- Long trousers and closed shoes must be worn.
- Protective gloves must always be worn when handling irritating or toxic substances or media that could contain potential pathogens (e.g. slurry or reactor sludge). Furthermore, safety goggles must always be worn during activities where there is a risk of splashing - we work with pressurised systems! Unknown microorganisms must always be regarded as pathogenic.
- Safety goggles must also always be worn when working with acids and bases. (Work with acids and bases may not be carried out in the practical course without a supervisor)

## 1.4. Behaviour in dangerous situations

-   General behaviour: **D**-**A**-**R**-**E** (**D**on't panic, **A**larm, **R**escue, **E**xtinguish)  
-   Health and safety violations, near-accidents and any accidents at work must be reported to the lab course supervisors.

# 2. Introduction

By definition, biogas is a combustible, volatile gas produced by the anaerobic fermentation of biomass. The main components are methane (CH4, 50-75%) and carbon dioxide (CO2, 25-50%). There are also smaller amounts of nitrogen (N2), ammonia (NH3), hydrogen (H2), hydrogen sulphide (H2S), water vapour (H2O), oxygen (O2) and other trace gases. The exact composition depends heavily on the substrate composition and the operating mode of the bioreactor (BMVIT, 2014). The production of biogas is a sustainable and ecological way of generating energy, as no climate-active greenhouse gases are released under optimal conditions. Furthermore, the use of organic residues as a substrate source can be promoted, which simultaneously solves problems associated with waste treatment and disposal. In addition to important ecological effects in the areas of environmental and climate protection, the anaerobic digestion of agricultural waste also offers socio-economic advantages. Another advantage is that the fermentation residues produced, which generally have an improved fertilising effect, a reduced number of pathogens and reduced odour pollution compared to the original substrates, can be applied directly to fields on site (Goberna et al., 2011; Insam et al., 2015).

In agricultural plants, liquid manure (slurry), which is produced during animal husbandry on the farms, is usually used as a basic substrate for biogas production. The use of liquid manure is de facto free of charge, it has a suitable water content and is usually produced in large quantities. However, due to the limited gas formation potential (low C/N ratio), it makes sense to also ferment other, energetically valuable materials as so-called co-substrates (Kaiser, 2007). For example, other agricultural waste products (straw, crop waste, etc.), industrial residues (from bakeries, abattoirs, dairies, breweries, etc.), municipal waste (e.g. shrub cuttings) and collected organic waste from private households can be used for this purpose. In recent years, "NAWARO" plants (renewable raw materials) such as maize, soya, beet or grain, which are planted exclusively for the production of biogas, have also been increasingly used. Although extremely efficient in energy production, the ethical question must be raised as to whether potential foodstuffs should be used for energy production. NAWARO plants are often in direct competition for land with the feed and food industry and the huge monocultures required for this are also questionable from an ecological perspective (EU, 2014). In agricultural plants, liquid manure (slurry), which is produced during animal husbandry on the farms, is usually used as a basic substrate for biogas production. The use of liquid manure is de facto free of charge, it has a suitable water content and is usually produced in large quantities. However, due to the limited gas formation potential (low C/N ratio), it makes sense to also ferment other, energetically valuable materials as so-called co-substrates (Kaiser, 2007). For example, other agricultural waste products (straw, crop waste, etc.), industrial residues (from bakeries, abattoirs, dairies, breweries, etc.), municipal waste (e.g. shrub cuttings) and collected organic waste from private households can be used for this purpose. In recent years, "NAWARO" plants (renewable raw materials) such as maize, soya, beet or grain, which are planted exclusively for the production of biogas, have also been increasingly used. Although extremely efficient in energy production, the ethical question must be raised as to whether potential foodstuffs should be used for energy production. NAWARO plants are often in direct competition for land with the feed and food industry and the huge monocultures required for this are also questionable from an ecological perspective (EU, 2014). 

Apart from the substrate (mixture) used, the biogas production process also depends on a number of other parameters, such as temperature, substrate mixing, feed quantity and pH value. The choice of temperature in particular is decisive for the efficiency of the biogas plant and enables operators to control the process. Nowadays, large-scale plants are usually operated under mesophilic (30-40 °C) or thermophilic (50-60 °C) conditions (Jain et al., 2015). However, recent studies show that the gap between these two temperature ranges is particularly interesting, as the advantages of both ranges can be combined here and optimal biogas yields can be achieved (Hupfauf et al., 2018; Tian et al., 2018). The advantages of mesophilic biogas production are high process stability (Labatut et al., 2014) and the low energy required to maintain a constant temperature in the bioreactor. Thermophilic fermentation, on the other hand, leads to better hygienisation of the digestate produced (Sahlström, 2003) and allows higher metabolic rates of the microorganisms involved.

The aim of this lab course is to demonstrate the possible microbial resource utilisation of materials generally declared as "waste". This is to be illustrated in the form of an anaerobic fermentation experiment with an agricultural residue (cattle manure). In order to demonstrate the influence of various process parameters, the students should decide in groups which adjustments they want to make during the experiment and then observe their effects. In addition to comparing the measured biogas yield and composition, the aim is to familiarise students with the basic parameters for monitoring a biogas plant. In addition, the hygienisation potential will be assessed with the help of a plating experiment on selective media. Selected pure cultures will also be identified using molecular biology.

## 2.1. The process of anaerobic digestion

In general, the process of anaerobic digestion can be divided into four main steps (see Fig. 1). During the initial hydrolysis, which determines the speed of the entire process, especially for substrates that are difficult to degrade (Hasegawa et al., 2000), organic polymers are broken down into smaller components (sugars, amino acids, fatty acids, etc.). In addition to obligate anaerobic microorganisms, facultative anaerobic species are also active at this stage. Acidogenic microorganisms subsequently form carbon dioxide (CO2), hydrogen (H2), ammonium (NH4) and organic acids (e.g. propionic, butyric or valeric acid) from these molecules. In the course of the third phase, the acetogenic phase, secondary fermentative bacteria form acetate, H2 and CO2.

These endergonic reactions would not take place under standard conditions, or only slowly, but the local proximity of syntrophic microorganisms and the immediate conversion of the resulting products by methane-forming archaea enable this biochemical metabolic pathway (Conrad et al., 1986).

In methanogenesis, a fundamental distinction can be made between three different pathways (see Table 1). In hydrogenotrophic methane formation, CH4 is formed by the reduction of CO2 with H2. In acetoclastic methane formation, which is quantitatively the most important reaction pathway, CH4 and CO2 are obtained from the cleavage of acetate (Ahring et al., 2003). In a third possible metabolic pathway, methyl compounds (C1 compounds) are used. In addition, so-called homoacetogenic bacteria can also form new acetates, which is referred to as homoacetogenesis (Boe, 2006). Conversely, acetate can be converted into CO2 and H2 by SAOB (syntrophic acetate-oxidising bacteria) through syntrophic acetate oxidation (SAO). The resulting products are then frequently utilised by syntrophically associated hydrogenotrophic methanogens to form CH4. This results in an interspecies transfer of H2 or CHO2-, known as IHT (interspecies hydrogen transfer). Which metabolic pathway is active in a biogas plant always depends on the process conditions, above all the temperature.

Table 1: Selection of important metabolic pathways of methanogenesis and their thermodynamic potential.  

|Reaction formula   |ΔG0 \[kJ mol<sup>-1</sup> CH<sub>4</sub>\] |Representative    |
|---|---|---|
|CO<sub>2</sub> + 4 H<sub>2</sub> --> CH<sub>4</sub> + 2 H<sub>2</sub>O   |-135   |nearly all methanogens    |
|4 HCOOH --> CH<sub>4</sub> + 3 CO<sub>2</sub> + 2 H<sub>2</sub>O    |-130   |nearly all methanogens    |
|4 CO + 2 H<sub>2</sub>O --> CH<sub>4</sub> + 3 CO<sub>2</sub>   |-196   |Methanothermobacter, Methanosarcina    |
|4 CH<sub>3</sub>OH -->3 CH<sub>4</sub> + CO<sub>2</sub> + 2 H<sub>2</sub>O   |-105   |Methanosarcina, methylotrophe Methanogene    |
|CH<sub>3</sub>OH + H<sub>2</sub> --> CH<sub>4</sub> + H<sub>2</sub>O   |-113   |Methanomicrococcus, Methanosphaera   |
|CH<sub>3</sub>COOH --> CH<sub>4</sub> + CO<sub>2</sub>    |-33    |Methanosarcina, Methanosaeta   |

# 3. Material and methods

## 3.1. Experimental setup

### 3.1.1. Reactor system

Schott bottle reactors have proven themselves for years as robust and easy-to-operate reactor systems on a small laboratory scale. They can be operated either as batch systems or semi-continuous reactors and are therefore extremely flexible in their mode of operation. The main disadvantages are the lack of integrated gas measurement or storage systems, which means that the reactors have to be checked daily, including gas sampling, to prevent the pressure in the reactor system from becoming too high. In addition, there is always a risk of leaks in such a pressurised system, which can lead to significant errors in gas measurement. In addition, increased safety precautions are always required when working with reactors of this type, for example laboratory goggles must always be worn.

We use modified laboratory bottles (2.35 litre volume) with three openings at the top (Fig. 2). These openings allow the connection of various valves, taps or measuring devices and ensure a versatile and customisable use of the reactors. Only one opening (on the side at the top of the reactor) is required for the practical course; the second and third openings are sealed airtight with appropriate sealing caps and suitable sealing rings. A gas-tight brass ball valve is screwed onto the remaining opening. The ball valve is used for feeding, sampling and gas measurement of the reactors. Silicone sealing rings and Teflon sealing tape are used during assembly to ensure complete tightness. To reduce the risk of flying glass splinters in the event of glass breakage, the reactors are encased in a safety net.

### 3.1.2. Filling the reactors

The reactors are filled together on the first day of the practical course (1 December 2023). The subsequent incubation of the reactors over the weekend before the actual start of the experiment on Monday (d0) enables the system and the microorganisms involved to adapt to the changed conditions and allows the stable operation (without start-up phase) to be investigated during the practical course. For filling, the upper blue lid is unscrewed and 1 litre of sieved cattle slurry (\< 2 mm) is filled in using a measuring cylinder. The slurry must be stirred thoroughly beforehand to ensure a uniform substrate in all reactors. The reactor is then tightly closed again and checked for leaks. To do this, a slight overpressure (approx. 0.5 bar) is generated via the ball valve using a bicycle pump (1-2 pump strokes) and the reactor is kept under water. If air bubbles are recognisable, the corresponding point must be better sealed or tightened. The sealed reactors are then incubated at 37 °C with the ball valve closed. Over the weekend, the reactors are shaken daily for 10 seconds and the biogas produced is drained off.

### 3.1.3. Experiment start

On the first day of the trial (d0), the reactors are prepared by the respective groups according to their chosen control parameter. The following adjustment parameters can be changed (each group decides on one parameter):

- Feeding quantity: 50 -- 200 mL\
- Temperature: 10 -- 60 °C\
- Co-substrate: Waste oil and larvae (Hermetia illucens) Residual substrate\
- Co-substrate (waste oil) concentration: 1 -- 20 g/L\
- Shaking: 10 -- 150 rpm

**IMPORTANT**: In addition to their four reactors (2 values of the control parameter x 2 replicates), each group also maintains two control reactors. These reactors are operated with the following reference parameters for the entire duration of the experiment: 37 °C, 100 mL feed (without co-substrate), 0 rpm. An average value from both control reactors then serves as a reference for the analysed parameters of the respective group.

<br>

### 3.2. Sampling and feeding

**ATTENTION**: Sampling and feeding is always carried out after the gas measurements (3.3.1, 3.3.2), as the reactors are pressurised up to this point. Failure to observe this may result in injury and unintentional spraying of the reactor contents!

**Durchführung:**\
To take a sample, a clean 100 mL plastic syringe is attached to the silicone tube of the ball valve. The reactor is then tilted until the liquid phase moves to the top of the Schott bottle. The headspace (gas space) is located at the bottom. The valve is opened and the plastic syringe is slowly drawn up to the 100 ml mark. Close the valve and remove the syringe. Only then may the reactor be set up vertically again! If a blockage occurs during sampling, the opening of the syringe and the ball valve (reactor in upright position!) must be cleaned with a pointed object. The sample taken is transferred to three labelled 2 mL Eppendorf tubes (stored at -20 °C) and a labelled Erlenmeyer flask and is now ready for subsequent analyses. For feeding, a clean 100 mL plastic syringe is filled with 100 mL substrate (mixture) (stir well beforehand!). This is then connected to the ball valve and emptied into the reactor after opening the valve. The reactor does not have to be turned upside down! The ball valve is then completely closed again, the reactor is shaken horizontally for 10 seconds and placed back at its incubation location. The same syringe can be used for feeding all reactors, as long as the substrate mixture is uniform! As small quantities of substrate or reactor sludge can easily escape during sampling and feeding, always work with plenty of cellulose and then clean the workplace with ethanol (70%). IMPORTANT: If a group has selected the feeding quantity parameter, other quantities are fed or sampled. However, the amount of material removed must always be replenished with new substrate afterwards! Excess reactor sludge removed is collected and then disposed of. IMPORTANT: If a group has selected the co-substrate or co-substrate concentration parameter, feeding is always carried out with a substrate mixture!

## 3.3. Gas analyses

Determining the amount of gas is of particular interest in large-scale plants, as the biogas produced should bring the desired financial profit. For this purpose, there is generally a whole range of measuring devices that can measure the gas pressure in a certain volume (manometer), the volume displacement (eudiometer) or the flow rate (flowmeter) of the gas. All of these principles can also be applied on a laboratory scale, but in the practical course we limit ourselves to the pressure-based measurement of the gas volume using a manometer.

### 3.3.1. Pressure-based measurement of gas volume

The amount of gas produced each day is determined on the basis of pressure using a digital manometer. Procedure: The reactors are removed individually from the incubators and placed in a well-ventilated area (e.g. near the tilted window). The time the reactor spends outside the incubator must be minimised. Otherwise the process can be significantly disturbed and reproducible measurements are no longer possible. The connecting piece of the manometer is connected to the silicone tube at the end of the ball valve. The ball valve is then opened slowly and the differential pressure displayed between inside and outside the reactor is noted. It should be noted that the pressure gauge needs a certain amount of time to reach a constant value. If the pressure drops continuously, the tightness of the connection must be checked! ATTENTION: We are working with pressurised reactor systems here! This requires considered and calm action. It is essential to wear safety goggles during the pressure measurement!

**Evaluation**:\
The amount of biogas produced is then calculated using the following formula: Biogas \[NmL\]= (∆P \[hPa\] × headspace \[mL\]× DBF(T))/(1013 hPa)

The headspace volume of the reactors in the practical course is 1350 mL, the "dry biogas factor" (DBF, Richards et al. (1991)) for the corresponding temperature is taken from Table 2. The result is the amount of gas produced under standard conditions (0 °C, 1013 hPa), taking into account the water vapour contained (= dry biogas). Finally, the change over time of all analysed variants compared to the control as well as the accumulated gas production at the end of the test period are shown graphically (mean values ± standard deviation). 10 °C 20 °C 37 °C 45 °C 55 °C 60 °C DBF 0.953 0.909 0.824 0.773 0.697 0.658 Table 2: Temperature-specific "dry biogas factor" (DBF, Richards et al. (1991)) for the calculation of dry biogas.

### 3.3.2. Gas composition

The gas composition is measured using a mobile infrared gas analyser (IRGA; GA5000, Geotech, UK; Fig. 3). This device measures CO2, CH4, H2S, O2 and residual gas photometrically depending on the adsorption of the emitted infrared light by the gas sample. Each gas sample absorbs different amounts of radiation depending on the gases. Each IRGA can only measure the gases for which reference chambers have been installed. Other measuring methods such as gas chromatography or chemical processes must therefore be used to measure any other trace gases relevant to the process (e.g. H2, NH3). Regular calibration of the IRGA is important, which is carried out with a calibration gas and ambient air and must be performed every six months for the device. To demonstrate an alternative measurement method, H2S measurement using Dräger-Tubes will be demonstrated during the practical course (detailed instructions will be provided during the practical course). The H2S content in biogas is of great importance, as this gas causes corrosion damage to metal components (e.g. in combustion engines) in high concentrations (\> 200 ppm). Highly contaminated gas must therefore be purified before use. In addition, increased H2S concentrations in the anaerobic system are toxic to microorganisms, especially methanogens (at pH 7.8-8: 50% inhibition from 90 mg L-1; Koster et al. (1986)), and are also harmful to humans in the air we breathe (irritation from 100-200 ppm!).

**Execution**:\
For the measurement, 100 mL of biogas is removed from the reactor using a glass syringe. Like the pressure measurement, the sample is taken via the ball valve. The tip of the glass syringe is connected to the silicone tube and the valve is then carefully opened. The gas withdrawal can be precisely controlled by turning the ball valve slightly. Avoid opening the valve too quickly, as otherwise the plunger could be pushed out of the syringe and damage to the material or injuries could occur. The filled glass syringe is then connected to the IRGA and the measurement is started by pressing the PURGE button. Once the syringe is completely empty, the measurement must be stopped manually by pressing the FLUSH button again. After a short equilibration time, the concentrations of the gases CH4, CO2, H2S and O2 are displayed. The device must be purged with room air between each measurement (until CO2 and CH4 \< 0.2%)! Immediately after the analysis, the excess biogas is drained into the reactors, thus reducing the overpressure. Discharge takes place exclusively in the designated area (fume cupboard)! ATTENTION: As the reactors are still pressurised up to this point, the determination of the gas composition must also be carried out carefully and cautiously. This includes in particular the wearing of protective goggles!

**Evaluation**:\
The change over time of all biogas components (CH<sub>4</sub>, CO<sub>2</sub>, H<sub>2</sub>S, O<sub>2</sub>) is to be graphically represented. In addition, the methane yield (mL CH<sub>4</sub> g<sup>-1</sup> oTS) of the analysed treatments and the control should be calculated with the help of the gas composition. The choice of a suitable visualisation option is up to the respective groups.

## 3.4. Physicochemical analyses

### 3.4.1. pH value

Ein wichtiges Merkmal für die Charakterisierung eines Bioreaktors ist der Säuregrad (pH-Wert). Vor allem die Nährstoffverfügbarkeit aber auch die Toxizität gewisser Stoffe (H2S, NH3) hängt vom pH-Wert ab. Bei den meisten pH-Metern handelt es sich um potentiometrische Geräte, bestehend aus einer mit Pufferlösung gefüllt Glaskugel. An die Oberfläche der Glaskugel lagern sich in dünner Schicht Protonen an, wodurch sich, je nach pH-Differenz zwischen Innenseite und Außenseite, eine galvanische Spannung aufbaut. Diese Spannung wird mit Hilfe zweier Elektroden, der Messelektrode innerhalb der Glaskugel und einer Referenzelektrode außerhalb, gemessen. Durchführung: Das pH-Meter muss vor der ersten Messung immer kalibriert werden (entsprechend der im Praktikumslabor ausliegenden Anleitung)! Anschließend erfolgt die Messung der Schlammproben in den Erlenmeyerkolben. Sobald das pH-Meter einen konstanten Wert anzeigt (dies wird zudem durch ein entsprechendes Symbol am Gerät angezeigt), wird der Wert notiert. Zwischen den Proben muss die Glaselektrode stets mit A.d. gespült werden. Nach der Analyse wird die Elektrode noch einmal gründlich gespült, vorsichtig mit Zellstoff abgetrocknet und in die Aufbewahrungslösung (KCl) getaucht. Da es sich bei dem im Praktikum verwendeten Gerät um ein Temperatur-korrigiertes pH-Metern handelt, müssen die Proben nicht unter einheitlicher Temperatur gemessen werden. Große Abweichungen zur Lufttemperatur ziehen allerdings (beträchtlich) längere Messzeiten nach sich. ACHTUNG: Da bei der Eichung des pH-Meters eine Säure benötigt wird, ist das Tragen einer Schutzbrille und Handschuhen vorgeschrieben!

**Evaluation**:\
Der Verlauf des pH-Werts soll grafisch über die Zeit für alle Ansätze im Vergleich zur Kontrolle dargestellt werden (Mittelwert ± Standardabweichung).

### 3.4.2. Electrical conductivity (EC)

Die elektrische Leitfähigkeit (= Konduktivität) gibt an, wie gut ein Stoff elektrischen Strom leiten kann. In einer Flüssigkeit hängt die Leitfähigkeit eines Stoffes von der Anzahl an gelösten Ionen ab. Die elektrische Leitfähigkeit korreliert deshalb stark mit der Ammoniumkonzentration, es finden sich aber auch vielerlei andere Salze im Reaktorschlamm. Eine zu hohe elektrische Leitfähigkeit, und somit zu viele Ionen in der Lösung, können den Prozess der anaeroben Vergärung durch ungünstige osmotische Verhältnisse stören (Ma et al., 2018). Die Messung der EC erfolgt im Praktikum mit Hilfe einer Leitfähigkeits-Elektrode, analog zur Messung des pH-Werts. Durchführung: Die Messung der Proben erfolgt wahlweise vor oder nach der pH-Messung (3.4.1) im selben Erlenmeyerkolben. Dazu wird die EC-Elektrode in den unverdünnten Reaktorschlamm getaucht und der Messwert am Gerät nach Einpendeln (konstanter Wert für ca. 5 s) notiert. Die Erlenmeyerkolben müssen vor der Messung unbedingt immer geschwenkt werden, um eine gut durchmischte, homogene Probe zu gewährleisten.

**Evaluation**:\
Der Verlauf der elektrischen Leitfähigkeit soll grafisch über die Zeit für alle Ansätze im Vergleich zur Kontrolle dargestellt werden (Mittelwert ± Standardabweichung).

### 3.4.3. FOS/TAC ratio

Der FOS/TAC Wert beschreibt das Verhältnis von flüchtigen organischen Säuren (FOS) zur Carbonat-Alkalinität (Totales Anorganisches Carbonat, TAC). Die Alkalinität im Reaktorschlamm ist ein Maß für die alkalische Pufferkapazität des Systems und bestimmt, wie robust sich der pH-Wert gegenüber einer Anhäufung von Säuren verhält. Weist ein Bioreaktor eine hohe Alkalinität auf, führt eine geringfügige Akkumulation von VFAs nicht umgehend zur Störung des Prozesses. FOS/TAC ist deshalb ein Standardparameter zur Einschätzung der Stabilität eines Bioreaktors. Die Messung erfolgt typischerweise über Titration zu den beiden pH-Werten 4.4 (FOS) und 5.0 (TAC). Im Zuge des Praktikums erfolgt die Titration mit einem automatischen Titrator (Abb. 4) und 0.1 N Schwefelsäure.

**Execution**:\
Eine geringe Menge an Probe (z.B. 1 mL) wird in einem Becherglas mit A.d. auf 50 mL aufgefüllt und mit einem kleinen Magnetrührer versehen. Anschließend wird das Becherglas auf den automatischen Titrator gestellt und die pH-Sonde sowie der Schlauch zur Säure-Dosierung in die Flüssigkeit getaucht. Die Glaselektrode darf dabei auf keinen Fall vom Magnetrührer getroffen werden, da sie dadurch leicht beschädigt werden kann! Der Titrator wird gestartet und der Rührer auf mittlerer Stufe eingeschalten. Die Steuerung des Geräts erfolgt über die angeschlossene Fernbedienung:

\<User Meth\> drücken, bis am Display Methode laden erscheint \<Enter\> \<Select\> drücken, bis am Display FOSTAC erscheint \<Enter\> \<Start\> Am Ende der Messung werden die jeweiligen Volumina an Säure, die zur Erreichung von pH 5 bzw. 4.4 benötigt wurden angezeigt. Mit <Enter> kann zwischen beiden Punkten hin und her gewechselt werden. WICHTIG: Vor der ersten Messung jeder Gruppe muss die pH-Elektrode neu kalibriert werden. Die Kalibrierung erfolgt ebenfalls über die Fernbedienung des Titrators: \<Mode\> drücken, bis CAL am Display erscheint \<Enter\> \<Start\> Die Elektrode wird in Puffer 1 (pH 7) getaucht \<Enter\> Nach Aufforderung am Display wird die Elektrode in Puffer 2 (pH 4) getaucht \<Enter\> Am Ende des Vorgangs werden die Kalibrierungspara-meter angezeigt und es kann direkt mit der ersten Messung entsprechend dem oben erläuterten Vorgehen begonnen werden.

**ATTENTION**:\
Da sowohl bei der Eichung der pH-Elektrode als auch bei der Titration Säuren verwendet werden, ist das Tragen einer Schutzbrille und Handschuhen vorgeschrieben!

**Evaluation**:\
Aus den erhaltenen Messwerten (Säurevolumen) errechnet man anschließend das FOS/TAC Verhältnis anhand folgender Formel:

FOS⁄TAC \[(mg/L)/(mg/L)\]=((├ B×20/V_P ×1.66┤-0.15)×500×V_P)/(A×5000)

A = Volumen \[mL\] der Säure bis pH 5.0 B = Volumen \[mL\] der Säure von pH 5.0 bis pH 4.4 VP = Volumen \[mL\] der Probe Der FOS/TAC Wert soll grafisch über die Zeit für alle Ansätze im Vergleich zur Kontrolle dargestellt werden (Mittelwert ± Standardabweichung).

### 3.4.4. Ammonium content (NH4)

Der Ammoniumgehalt in Bioreaktoren ist ein wichtiger Kontrollparameter zur Überwachung des Prozesses. Hohe Konzentrationen können, insbesondere unter thermophilen Bedingungen, zu einer erheblichen Prozessstörung und einem damit einhergehenden Einbruch der Gasproduktion führen. Die Messung im Praktikum erfolgt mittels Fließinjektionsanalyse (FIA) unter Verwendung der OPA/NAC-Methode (Meseguer-Lloret et al., 2002). Dabei reagiert das Ammonium mit ortho-Phthaldialdehyd (OPA) und N-Acetyl-Cysteine (NAC) unter alkalischen Bedingungen und wird, nach Anregung bei 415 nm, an einem Hochleistungsflüssigkeitschromatographie-System (High performance liquid chromatography -- HPLC) (Abb. 5) gemessen. Alternativ kann man Ammonium auch klassisch mit einem Photometer (z.B. Berthelot-Reaktion) oder mit Hilfe von Küvetten Schnelltests (Nanocolor) messen.

**Execution**:\
Die aufgetauten Proben werden für 10 min bei 20,000 g zentrifugiert. Anschließend wird der Überstand 1:10 mit A.d. verdünnt und in kurze Eprouvetten steril-filtriert (Porenweite: 0.2 µm, Filtermaterial: regenerierte Cellulose RC). Davon wird anschließend eine 1:5 Verdünnung mit A.d. hergestellt und 250 µL in eine 96-Well Platte (eine gemeinsame Platte für alle Gruppen, Positionen unbedingt notieren!) pipettiert. Das restliche Filtrat muss unbedingt aufbewahrt (und verschlossen auf 4 °C gelagert) werden, da es für die VFA Messung (3.4.5) benötigt wird. Sobald eine Gruppe alle Proben auf die Platte pipettiert hat, muss sie umgehend abgedeckt und auf 4 °C gestellt werden. Andernfalls droht ein rasches Entweichen der flüchtigen Bestandteile! Sobald alle Gruppen fertig sind, wird die Platte mit Aluminium-Klebefolie versiegelt, ins Analytik-Labor gebracht und in das HPLC Gerät geladen.

**Evaluation**:\
Nach der Analyse erhalten wir ein PDF-Datenblatt mit NH4-N Konzentrationen in mg L-1. Die zeitliche Veränderung der Ammoniumkonzentration (Mittelwert ± Standardabweichung) soll dann grafisch dargestellt werden.

### 3.4.5. Volatile fatty acids (VFAs)

Flüchtige Fettsäuren (Formiat, Acetat, Propionat, Butyrat, Valeriat) sind wichtige Intermediär-Produkte der anaeroben Vergärung und ermöglichen die genaue Überwachung der Vorgänge innerhalb eines Bioreaktors. Eine Akkumulation weist allgemein auf eine zu hohe Beschickung (Fütterung) oder ein Ungleichgewicht der einzelnen Phasen des Prozesses hin. Zudem kann ein gehäuftes Auftreten von Propionat beispielsweise zur Hemmung der Gasproduktion führen. Deshalb verwendet man oft das Verhältnis von Acetat zu Propionat als Indikator für die Prozessstabilität (Weiland, 2008). Eine Akkumulation von Butyrat oder Valeriat, insbesondere derer Iso-Formen, ist ein weiterer deutlicher Hinweis auf Stabilitätsprobleme (Drosg, 2013). Die Messung der flüchtigen Fettsäuren erfolgt im Praktikum mit Hilfe von HPLC (Abb. 5). Dabei spielt die ähnliche Polarität der gesuchten Verbindungen eine zentrale Rolle, da diese Eigenschaft dazu genutzt wird, Stoffe an einer stationären Phase (Trennsäule) zu binden. Anschließend werden über die Veränderung der Polarität des Laufmittels (Eluent) die einzelnen Stoffe von der Trennsäule gewaschen und getrennt gesammelt. Zur Identifikation der gesammelten Verbindungen wird die jeweilige Retentionszeit herangezogen.

**Execution**:\
Für die VFA-Messung können die Filtrate (bereits 1:10 verdünnt), die im Zuge der Ammonium Bestimmung (3.4.4) hergestellt wurden, verwendet werden. Die Proben werden direkt auf eine zweite (gemeinsame) 96-Well Platte pipettiert, wobei ebenfalls die jeweilige Position exakt notiert werden muss! Da flüchtige Fettsäuren in der Regel sehr schnell ausgasen können und damit die Messung einem großen Fehler unterliegen würde, muss die Platte bis zur endgültigen Messung immer auf 4 °C gelagert werden. Sobald alle Gruppen ihre Proben geladen haben, wird die Platte mit Klebefolie fest versiegelt.

**Evaluation**:\
Als Ausgabe der HPLC erhält man ein so genanntes Chromatogramm, bei der verschiedene Spitzen (Peaks) seriell aufeinander folgen. Jeder Peak stellt eine spezifische chemische Verbindung dar und die Fläche unter der Spitze beschreibt dessen Menge (Berechnung über Integration). Die genaue Menge muss normalerweise über eine Standard-Messung ermittelt werden. In unserem Fall ist dieser Schritt jedoch nicht mehr notwendig, da die Methode bereits etabliert ist. Wir erhalten die Daten in Form eines PDF-Datenblatts mit Konzentrationen in mmol L-1, welche anschließend grafisch über den Versuchszeitraum dargestellt werden sollen.

### 3.4.6. Chemical oxygen demand (COD)

Der chemische Sauerstoffbedarf ist ein wichtiger Parameter in der Abwasserbehandlung und der Biogaserzeugung und ein Maß für die Summe aller Lösung vorhandenen (durch Dichromat) oxidierbaren Stoffen. Mit ihm lässt sich der Abbaugrad im Reaktor über die Zeit überwachen und zudem das theoretische Biogaspotential abschätzen. Man geht davon aus, dass bei einem vollständigen Abbau von 1 g CSB, ca. 350 mL Methan entstehen (Reinhold, 2004). Der gesamte CSB-Gehalt setzt sich aus dem partikulären und dem gelösten CSB zusammen. Die Bestimmung des CSB kann entweder über Titration oder photometrisch erfolgen. Im Zuge des Praktikums werden photometrische Schnellkits zur Bestimmung des Gesamt-CSBs verwendet. Inkubation und Messung erfolgen in dafür vorgesehenen Geräten (NANOCOLOR Thermoblock und Photometer; Abb. 6).

Abb. 6: (A) NANOCOLOR Thermoblock zur Inkubation der Rundküvetten und (B) NANOCOLOR Photometer zur Messung der Rundküvetten für die CSB Bestimmung im Reaktorschlamm.

**Execution**:\
Die aufgetauten Proben werden zuerst 1:10 mit A.d. verdünnt. Jeweils 2 mL der Lösung werden in NANOCOLOR Rundküvetten pipettiert. Die Küvetten werden daraufhin geschüttelt (ca. 5 s) und für 30 min bei 160 °C im NANOCOLOR Heizblock inkubiert. Nach neuerlichem Schütteln und einer ca. halbstündigen Abkühlphase auf Raumtemperatur werden die Küvetten mit dem NANOCOLOR Photometer gemessen.

**Evaluation**:\
Der chemische Sauerstoffbedarf für alle Ansätze soll in Form eines Balkendiagramms im Vergleich zur Kontrolle dargestellt werden (Mittelwert ± Standardabweichung). ACHTUNG: Die Chemikalien in den NANOCOLOR Küvetten sind stark ätzend und gesundheitsschädlich! Deshalb gilt beim Befüllen der Küvetten Brillen- und Handschuhpflicht! Nach dem Befüllen müssen die Küvetten sorgfältig verschlossen werden. Sowohl die Inkubation im Heizblock als auch das anschließende Abkühlen der Küvetten muss unter dem Abzug stattfinden! Die verwendeten Küvetten werden in die Box zurückgestellt und anschließend von den Praktikumsleitern entsorgt.

### 3.4.7. Dry matter (DM) and organic dry matter (oDM)

Da organisches Material in der Regel verschieden viel Wasser beinhaltet, stellt die Trockensubstanz eine wichtige Bezugsgröße dar und ermöglicht einen direkten Vergleich zwischen verschiedensten Substraten. Bei der anaeroben Vergärung wird organisches Material abgebaut und zu einem großen Teil in Biogas umgewandelt. Dies führt zu einer Reduktion der (organischen) Trockensubstanz, weshalb TS und oTS wichtige Messgrößen zur Kontrolle von Biogas Reaktoren darstellen. Durch kontinuierliche Beobachtung der Werte kann die Fütterungs-Strategie beurteilt und eine zu hohe bzw. geringe Rate erkannt werden. Zudem weist eine plötzliche Erhöhung auf eine Prozessstörung hin und ermöglicht es dem Betreiber rechtzeitig zu reagieren.

**Execution**: Schlammproben (mindestens 30 g) aus der pH-Messung (3.4.1) bzw. der EC-Messung (3.4.2) werden in tarierte Glaspetrischalen (Tara unbedingt notieren!) eingewogen, und der Gewichtsverlust bei 105 °C über Nacht bestimmt. Anschließend wird ca. 1 g der getrockneten Probe in Keramikschälchen eingewogen (ebenfalls Tara notieren!) und für 5 Stunden bei 550 °C im Muffelofen verascht (laut BGBl II 292/2001). Die Gefäße müssen sowohl nach dem Trocknen bei 105 °C als auch nach dem Muffeln in einem Exsikkator unter Ausschluss von Sauerstoff abgekühlt werden.

**Formulas for calculation**:

TS \[% FM\] = Trockenrückstand \[g\] x 100 / FM \[g\] WG \[% FM\] = 100% - TS \[% FM\] aoTS \[% TS\] = Muffelrückstand \[g\] x 100 / TS \[g\] oTS \[% TS\] = 100% - aoTS \[% TS\]

FM ... Frischmasse WG ... Wassergehalt aoTS ... anorganische Trockensubstanz

oTS \[% FM\] = TS \[% FM\] x oTS \[% TS\]

**Evaluation**:\
TS und oTS (angegeben in Prozent der Frischmasse) sollen grafisch über den Zeitverlauf für alle Ansätze und die Kontrolle dargestellt werden (Mittelwert ± Standardabweichung).

### 3.4.8. Carbon:Nitrogen ratio (C:N)

Das Verhältnis von Kohlenstoff zu Stickstoff ist in der Umweltmikrobiologie von großer Bedeutung, da der bioverfügbare Stickstoff für viele Wachstumsprozesse einen limitierenden Faktor darstellt. Andererseits ist der enthaltene Kohlenstoff die Grundlage für Biogas (CH4, CO2) bei der anaeroben Vergärung und limitiert deshalb den gesamten Prozess. Aus diesem Grunde sollte das C/N-Verhältnis bei der Produktion in einem gewissen Bereich (ca. 20-30) liegen (Yadvika et al., 2004). Bei einem zu niederen Verhältnis, kann es zur Akkumulation von Ammonium und einem damit verbundenen, für Methanogene toxischen Anstieg des pH-Werts im Reaktor kommen (Wang et al., 2012). Das C/N-Verhältnis im Bioreaktor kann durch Zugabe von unterschiedlichen Co-Substraten angepasst und optimiert werden. Die Menge an Kohlenstoff und Stickstoff wird im Zuge des Praktikums mittels Elementaranalyse bestimmt (Abb. 7). Dabei werden die Proben bei 850 °C verbrannt und das Verhältnis der entstehenden Gase (CO2 und N2) mit einem Infrarot Gasanalysator (IRGA) bestimmt.

**Execution**:\
Proben aus der TS Bestimmung (3.4.7) werden zu einem feinen Pulver gemörsert und in Zinn Folien, möglichst unter Ausschluss von Restluft, eingewogen (max. 100-150 mg). Anschließend erfolgt die Messung im Elementar-Analysator. Die Zinnfolie darf niemals ohne Handschuhe berührt werden, da dies zu einer Beeinträchtigung der Messung führen könnte.

**Evaluation**:\
Das C/N-Verhältnis wird aus den gemessenen Konzentrationen von Kohlenstoff und Stickstoff berechnet. Die zeitliche Veränderung des C/N-Verhältnisses soll grafisch für alle Ansätze im Vergleich zur Kontrolle dargestellt werden (Mittelwert ± Standardabweichung).

## 3.5. Hygienization potential

Die Verwendung von Gärresten als Düngemittel erwies sich in vielerlei Hinsicht als vorteilhaft gegenüber nicht fermentiertem Mist und Gülle. Ein wichtiger Grund dafür ist die Hygienisierung des Substrats, die im Zuge der anaeroben Vergärung erfolgt. Dadurch kann die Sicherheit bei der Ausbringung auf Wiesen und Felder erhöht werden. Die Effizienz dieser Hygienisierung ist allerdings von verschiedenen Parametern wie beispielsweise Temperatur und Fütterungsstrategie abhängig und kann mitunter deutlich unterschiedlich ausfallen. Wir werden im Zuge des Praktikums das Hygienisierungspotential der jeweiligen Reaktorsysteme mit einem klassischen, mikrobiologischen Plattierungsansatz bestimmen. Dabei werden drei verschiedene Selektivmedien (TBX Chromocult, XLT-4, PALCAM) zur Detektion relevanter Pathogene (Coliforme Bakterien, Salmonellen, Listerien) verwendet. Alternativ könnte man pathogene Organismen auch molekularbiologisch nachweisen. Typische Methoden hierfür wären PCR (nur qualitativ), qPCR, dPCR, ddPCR oder Sequenzierung. Zusätzlich zu den Selektivmedien wird auch die gesamte Keimzahl (auf Standardmedium) bestimmt.

**Preparations**:\
Am Beginn des Praktikums werden bereits ausreichend Platten für alle Analysetage hergestellt und anschließend bis zur Verwendung luftdicht verpackt auf 4 °C gelagert. Die Zubereitung erfolgt anhand der jeweiligen Datenblätter bzw. Tab 3. Menge Zutat 5.0 g Pepton aus Fleisch 2.5 g Hefeextrakt 1.0 g Glucose 15.0 g Agar 1000 mL Auf 1000 mL deionisiertes Wasser auffüllen auf pH = 7 einstellen (25 °C) Tab 3: Zusammensetzung des Standardmediums zur Bestimmung der Gesamtkeimzahl.

**Execution**:\
Entnommene Reaktorproben werden 1:10 mit steriler isotonischer NaCl-Lösung (0.9% w/v) verdünnt und für 15 min bei 200 rpm geschüttelt. Nach einer Sedimentationsphase von 30 min werden Verdünnungen in 10er Schritten (100, 10-1, 10-2 für Selektivmedien; 10-5, 10-6, 10-7 für Standardmedium) angefertigt und jeweils ca. 25 µL auf Agar-Platten ausplattiert. Steriles Arbeiten ist hier essentiell wichtig! Die Platten werden für 24 h auf 37 °C inkubiert und anschließend ausgewertet. Herangezogen wird dabei jeweils nur jene Konzentration, welche die am besten auszählbare Anzahl an CFUs aufweist. Sollten selbst bei der niedrigsten Verdünnung keine CFUs erkennbar sein, werden die Platten weiter inkubiert und innerhalb der nächsten Tage erneut ausgewertet. Nach der Auszählung werden morphologisch interessante Kolonien auf eine Masterplatte mit Standardmedium übertragen. Mithilfe einer sterilen Pipettenspitze wird etwas Zellmaterial von freistehenden, klar abgegrenzten Einzelkolonien „gepickt". Dafür muss mit der Pippenspitze die Kolonie nur leicht berührt werden um etwas davon aufzunehmen (Die Pipette selbst bzw. die Saugfunktion der Pipette ist dafür nicht notwendig). Die Spitze wir dann mithilfe des zur Orientierung untergelegten Rasters in ein freies Kästchen auf der Masterplatte getupft ohne jedoch den Agar zu beschädigen. Die Masterplatte wird anschließend bei 37 °C inkubiert bis die gepickten Einzelkolonien klar sichtbar werden. Im Laborjournal muss anhand der durchnummerierten Kästchen notiert werden, welche Kolonie von welchen Platten (Standardmedium, TBX Chromocult, XLT-4, PALCAM) gepickt wurde damit eine nachträgliche Zuordnung möglich ist.

**Evaluation**:\
Die Anzahl an CFUs soll für beide Messtage grafisch dargestellt und mit der Kontrolle verglichen werden (Mittelwert ± Standardabweichung). Zudem soll die Reduktion der allgemeinen Keime bzw. Pathogene nach neun Tagen Laufzeit in Prozent angegeben werden. ACHTUNG: Die Supplemente zur Herstellung des XLT-4- und PALCAM-Agars sind stark ätzend. Bei der Herstellung dieser Medien gilt deshalb höchste Vorsicht und das Tragen von Schutzbrillen und geeigneten Handschuhe ist unumgänglich! Zudem dürfen die Agar-Platten nach der Kultivierung nicht mehr geöffnet werden, da sie stark angereicherte pathogene Mikroorganismen enthalten (**Exception**: Kolonie PCR 3.6.1 unter Laminar-Flow)! Für die Inkubation und Lagerung müssen die Platten mit entsprechenden Warn-Aufklebern versehen und nach der Auswertung bzw. im Falle der ersten Woche nach der Kolonie PCR umgehend autoklaviert werden.

## 3.6. Bio-molecular characterization of pathogens

### 3.6.1. Colony PCR

Allgemein werden bei der Polymerase Kettenreaktion (PCR) spezifische DNA Fragmente in großer Zahl vervielfältigt, womit auch die Analyse geringster DNA Mengen ermöglich wird. Bei der Kolonie PCR wird, im Gegensatz zur herkömmlichen PCR, keine reine DNA als Ausgangsmaterial verwendet. Vielmehr wird Zellmaterial (z.B. einer bakteriellen Kolonie) direkt überimpft und die enthaltene DNA anschließend amplifiziert. Auf diesem Wege lässt sich der zeitaufwendige und verhältnismäßig teure Schritt der DNA-Extraktion vermeiden.

**Execution**: Jede Gruppe untersucht fünf morphologisch interessante Kolonien von den Masterplatten (3.5) der ersten Woche. Zuerst wird ein Mastermix in ausreichender Menge (Anzahl untersuchter Proben + 1) vorbereitet. Dies geschieht in sterilen 0.5 mL Eppendorf-Tubes (Beschriftung nicht vergessen!) entsprechend dem Protokoll in Tab 4. Nach der Zubereitung muss das Gefäß fest verschlossen und für 5 s gevortext werden. Volumen \[µL\] Reagenz 12.5 VWR Red Taq DNA Polymerase 2x Mastermix, 1.5 mM MgCl2 0.5 Forward Primer: 27F (5'-AGA GTT TGA TCA TGG CTC A-3') 0.5 Reverse Primer: 1492R (5'-TAC GGT TAC CTT GTT ACG ACT T-3') 0.5 Bovines Serumalbumin (BSA, 2%) 11.0 PCR H2O 25 GESAMTVOLUMEN Tab 4: Mastermix für die Kolonie PCR Untersuchung ausgewählter Reinkulturen. Mengenangabe für eine Probe.

Anschließend werden je 25 µL Mastermix in sterile PCR-Tubes pipettiert und mit Zellmaterial beimpft. Hierfür werden geeignete Kolonien auf den Selektivagar-Platten ausgewählt und kleine Mengen davon mit sterilen Pipettenspitzen in die Tubes übertragen. Die fertigen Tubes werden für 5 s gevortext, kurz mit einer Tischzentrifuge zentrifugiert und in den Thermocycler (BioRad T100; Abb. 9) gesteckt. Das Programm wird nach den Angaben in Tab 5 gestartet. Nach Beendigung werden die Tubes auf -20 °C bis zur weiteren Verwendung gelagert.

**ATTENTION**: Für die Überimpfung des Zellmaterials müssen die Agar-Platten mit stark angereicherten Bakterien geöffnet werden. Dies darf ausschließlich unter dem Laminar Flow gemacht werden! Die Platten werden nur solange geöffnet, bis genug Zellmaterial entnommen wurde und werden anschließend umgehend wieder geschlossen. Die verwendete Pipettenspitze sowie die Laborhandschuhe werden in einen speziell gekennzeichneten Abfallbehälter entsorgt. Die Hände müssen nach diesem Arbeitsschritt desinfiziert werden! Phase Temperatur \[°C\] Dauer \[s\] Zyklen Initiale Denaturierung 95 300 1 Denaturierung 95 30 35 Primer-Annealing 54 30 35 Elongation 72 45 35 Finale Elongation 72 600 1 Ende 12 - - Tab 5: Programm für die Kolonie PCR Untersuchung ausgewählter Pathogene

### 3.6.2. DNA purification

Mit Hilfe von PCR amplifizierte DNA wird zumeist nachträglich aufgereinigt (DNA Clean-Up) um nachfolgende Analysen nicht durch Reste der PCR Reaktion zu stören. Im Praktikum geschieht die Aufreinigung mit einem speziellen PCR Clean-Up Kit (Sigma-Aldrich GenElute PCR clean-up). Alle Zentrifugationsschritte werden bei 11,000 g durchgeführt. Durchführung: Jede Probe wird 4:1 (z.B. 25 µL PCR Produkt + 75 µL Puffer) mit NT Puffer in 2 mL Eppendorf-Tube verdünnt (beschriften!). Anschließend werden NucleoSpin Extract Columns in frische 2 mL Eppendorf-Tubes gesteckt und mit den verdünnten Proben beladen. Nach Zentrifugation für 1 min (Durchfluss verwerfen) werden 600 µL NT3 Puffer hinzugefügt und abermals für 1 min zentrifugiert. Nun wird der Durchfluss verworfen und die Tubes für weitere 2 min zur Trocknung des Filters zentrifugiert. Die Filter werden in neue, sterile 1.5 mL Tubes gesteckt und mit 30 µL PCR Wasser überschichtet. Nach einer kurzen Inkubationsphase (1 min bei Raumtemepratur) wird für 1 min zentrifugiert (die Filter werden verworfen) und das Eluat bis zur weiteren Verwendung bei 4 °C im Kühlschrank gelagert.

### 3.6.3. Gel electrophoresis

Die Gelelektrophorese ist eine gängige Methode zur Überprüfung von PCR Proben. Im Praktikum erfolgt die Untersuchung auf einem 1%igem Agarose Gel. Die DNA Fragmente trennen sich entsprechend ihrer Länge auf und werden anschließend unter UV-Licht sichtbar gemacht. Eine gelungene Kolonie PCR sollte eine deutliche Bande pro Probe ergeben.

**Preparations**:\
Für die Zubereitung des Gels (ein Gel pro Gruppe) werden 150 mg Agarose und 15 mL 0.5x TAE Puffer in einen 100 mL Erlenmeyerkolben gefüllt. Die Mischung wird in der Mikrowelle gekocht, bis sich die Agarose komplett aufgelöst hat. Anschließend wird 1 µL DNA Farbstoff (SYBR Safe DNA gel stain) dazu pipettiert, gründlich geschüttelt und die Flüssigkeit in eine kleine Gelkammer gegossen. Kämme (wahlweise einer oder zwei) mit einer ausreichenden Anzahl an Zacken werden in das noch flüssige Gel gesteckt. Falls nötig, werden Luftblasen mit einer sterilen Pipettenspitze entfernt. Das Gel braucht in etwa 15 min, bis es vollständig ausgehärtet ist und beladen werden kann.

**Execution**:\
Nach Entfernen der Kämme wird das gehärtete Gel inklusive Halterung aus der Gelkammer entnommen und vorsichtig in die Elektrophorese-Kammer gelegt. Die Flüssigkeit in der Kammer muss das Gel komplett überdecken, ansonsten muss neuer 0.5x TAE Puffer nachgefüllt werden. Für die Beladung des Gels werden 1.5 µL Probe in die Taschen pipettiert. Dabei muss unbedingt die Reihenfolge notiert werden! In eine Tasche (üblicherweise die erste oder letzte) werden 1.5 µL DNA Ladder (GeneRuler Express) pipettiert. Sind alle Proben und die Ladder geladen, wird der Deckel der Elektrophorese-Kammer geschlossen und das Programm mit 100 V für 15 min gestartet. Nach Ablauf der Laufzeit wird das Gel entnommen, vorsichtig auf den UV-Tisch geschoben und unter geschlossenem Deckel untersucht. Das Ergebnis kann fotografisch festgehalten werden.

**ATTENTION**: Die markierte Sicherheitszone ist zu beachten! Dort stehende Gegenstände dürfen den Bereich nicht verlassen und separate Handschuhe müssen verwendet (und anschließend im Gefahrenstoff-Mülleimer entsorgt) werden. Die Elektrophorese-Kammer muss beim Hantieren unbedingt abgesteckt werden, da ansonsten die Gefahr eines Stromschlags droht. Das Gerät darf nur bei geschlossenem Deckel angesteckt und gestartet werden. Die Untersuchung des Gels am UV-Tisch darf nur bei beschlossenem Deckel stattfinden. Direktes UV Licht kann sonst zu Schäden, insbesondere der Augen, führen!

### 3.6.4. DNA quantification

Es gibt eine Vielzahl unterschiedlicher Methoden, um den DNA Gehalt in einer Probe bestimmen zu können. Im Praktikum erfolgt die Quantifizierung mit Hilfe eines Fluorometers (Promega Quantus). Alternativen dazu wären das Nanodrop System oder eine photometrische Messung mit PicoGreen DNA Farbstoff.

**Execution**:\
Jede Gruppe bereitet eine Stammlösung für alle ihre Proben (+ 1) vor. Dabei müssen je Probe jeweils 197.5 µL 1x TE-Puffer und 0.5 µL Farbstoff berechnet werden. Anschließend werden 198 µL der Stammlösung und 2 µL Probe in Analyse-Tubes pipettiert, gevortext und nach einer Inkubationszeit von 2 min im Quantus Fluorometer (Abb. 11) gemessen. Der Farbstoff bzw. alle Lösungen, die den Farbstoff enthalten, müssen so gut wie möglich vor Licht geschützt werden (Verwendung von Alufolie!), da die Substanz lichtsensitiv ist und schnell zerstört werden kann! Sollten die Messwerte oberhalb des Messbereich liegen, müssen die betroffenen Proben 1:10 mit 1x TE-Puffer verdünnt und erneut gemessen werden (der gesamte Ablauf muss dabei wiederholt werden!).

### 3.6.5. DNA sequencing and BLASTing

Es gibt unterschiedliche Techniken, wie DNA sequenziert werden kann. Neue System, wie z.B. Illumina, IonTorrent oder Nanopore können große Mengen an Sequenzen gleichzeitig analysieren und ermöglichen damit die Untersuchung ganzer Genome bzw. komplexer Umweltproben. Sanger Sequenzierung stellt eine bereits ältere Technologie dar, die sich allerdings aufgrund eines sehr niederen Preises und geringer Fehleranfälligkeit perfekt für die Sequenzierung einer Reinkultur eignet. Die Proben im Praktikum werden deshalb mittels Sanger Sequenzierung analysiert und die erhaltenen DNA Sequenzen anschließend geblastet. Unter Blasting versteht man den Vorgang, wenn eine DNA Sequenz mit einer bestehenden Datenbank verglichen wird und die am besten passenden Einträge gesucht werden. Dies ermöglicht die (taxonomische) Zuordnung einer unbekannten DNA Sequenz. Die Qualität der Datenbank ist entscheidend für das Ergebnis! Gängige Datenbanken für bakterielle Genfragmente (üblicherweise 16S) sind NCBI, Silva, Greengenes oder RDP.

**Execution**:\
Von jeder Probe werden 15 µL des gereinigten DNA Extrakts in sterile 1.5 mL Eppendorf-Tubes pipettiert. Zusätzlich werden 2 µL des verwendeten Forward-Primers (27F) zugegeben und die Tubes sorgfältig verschlossen. Jedes Tube wird mit einem bereitgestellten Prepaid Aufkleber der Sequenzierungs-Firma versehen. Anschließend müssen sowohl der Code auf dem Aufkleber als auch der dazu gehörende Probenname in das Online-Bestellformular eingetragen werden. Die fertigen Tubes werden in ein Luftblasen-Kuvert verpackt und müssen bis spätestens 16 Uhr in den Postkasten der Firma (1. UG, gegenüber dem Bodenlabor) geworfen werden. Binnen 24 h werden die Ergebnisse in Form von .fasta Dateien bereitgestellt. Die darin enthaltenen DNA Sequenzen werden dann mit Hilfe des online Blast Tools (https://blast.ncbi.nlm.nih.gov/Blast.cgi) analysiert. Als Referenzdatenbank verwenden wir die „Nucleotide collection" Datenbank von NCBI.

# 4. Bibliography

1.  Ahring, B.K., Angelidaki, I., de Macario, C.C., Gavala, H., Hofman-Bang, J., Elfering, S.O., Raskin, L., Stams, A., Westermann, P., Zheng, D. 2003. Biomethanation I. Springer.\
2.  BMVIT. 2014. Zusammensetzung von Biogas. Available at: http://www.biogas-netzeinspeisung.at/technische-planung/funktionsprinzip-einer-biogasanlage/zusammensetzung-von-rohbiogas.html. Accessed: 22.06.2018\
3.  Boe, K., 2006. Online monitoring and control of the biogas process. Institute of Environment and Resources, Technical University of Denmark.\
4.  Conrad, R., Schink, B., Phelps, T.J., 1986. Thermodynamics of H2-consuming and H2-producing metabolic reactions in diverse methanogenic environments under in situ conditions. FEMS microbiology letters. 38(6), 353-360.\
5.  Drosg, B. 2013. Process monitoring in biogas plants. IEA Bioenergy Task.\
6.  EU, 2014. State of play on the sustainability of solid and gaseous biomass used for electricity, heating and cooling in the eu. On the WWW. URL https://ec.europa.eu/energy/sites/ener/files/2014_biomass_state_of_play\_.pdf.\
7.  Goberna, M., Podmirseg, S., Waldhuber, S., Knapp, B., García, C., Insam, H., 2011. Pathogenic bacteria and mineral N in soils following the land spreading of biogas digestates and fresh manure. Applied soil ecology. 49, 18-25.\
8.  Hasegawa, S., Shiota, N., Katsura, K., Akashi, A., 2000. Solubilization of organic sludge by thermophilic aerobic bacteria as a pretreatment for anaerobic digestion. Water science and technology. 41(3), 163-169.\
9.  Hupfauf, S., Plattner, P., Wagner, A.O., Kaufmann, R., Insam, H., Podmirseg, S.M., 2018. Temperature shapes the microbiota in anaerobic digestion and drives efficiency to a maximum at 45° C. Bioresource technology. 269, 309-318.\
10. Insam, H., Gómez-Brandón, M., Ascher, J., 2015. Manure-based biogas fermentation residues--Friend or foe of soil fertility? Soil Biology and Biochemistry. 84, 1-14.\
11. Jain, S., Jain, S., Wolf, I.T., Lee, J., Tong, Y.W., 2015. A comprehensive review on operating parameters and different pretreatment methodologies for anaerobic digestion of municipal solid waste. Renewable and Sustainable Energy Reviews. 52, 142-154.\
12. Kaiser, F.L. 2007. Einfluss der stofflichen Zusammensetzung auf die Verdaulichkeit nachwachsender Rohstoffe beim anaeroben Abbau in Biogasreaktoren, Technische Universität München.\
13. Koster, I., Rinzema, A., De Vegt, A., Lettinga, G., 1986. Sulfide inhibition of the methanogenic activity of granular sludge at various pH-levels. Water Research. 20(12), 1561-1567.\
14. Laaber, M., 2012. Gütesiegel Biogas: Evaluierung der technischen, ökologischen und sozioökonomischen Rahmenbedingungen für eine Ökostromproduktion aus Biogas. Universität für Bodenkultur Wien, Wien.\
15. Labatut, R.A., Angenent, L.T., Scott, N.R., 2014. Conventional mesophilic vs. thermophilic anaerobic digestion: a trade-off between performance and stability? Water research. 53, 249-258.\
16. Ma, J., Amjad Bashir, M., Pan, J., Qiu, L., Liu, H., Zhai, L., Rehim, A., 2018. Enhancing performance and stability of anaerobic digestion of chicken manure using thermally modified bentonite. Journal of Cleaner Production. 183, 11-19.\
17. Meseguer-Lloret, S., Molins-Legua, C., Campins-Falco, P., 2002. Ammonium determination in water samples by using OPA-NAC reagent: a comparative study with nessler and ammonium selective electrode methods. International Journal of Environmental & Analytical Chemistry. 82(7), 475-489.\
18. Reinhold, F., 2004. TOC statt CSB -- oder "New CSB"? Korrespondenz Abwasser. 51(7), 705.\
19. Richards, B.K., Cummings, R.J., White, T.E., Jewell, W.J., 1991. Methods for kinetic analysis of methane fermentation in high solids biomass digesters. Biomass and Bioenergy. 1(2), 65-73.\
20. Sahlström, L., 2003. A review of survival of pathogenic bacteria in organic waste used in biogas plants. Bioresource technology. 87(2), 161-166.\
21. Taherzadeh, M.J., Karimi, K., 2008. Pretreatment of lignocellulosic wastes to improve ethanol and biogas production: a review. International journal of molecular sciences. 9(9), 1621-1651.\
22. Tian, G., Yang, B., Dong, M., Zhu, R., Yin, F., Zhao, X., Wang, Y., Xiao, W., Wang, Q., Zhang, W., 2018. The effect of temperature on the microbial communities of peak biogas production in batch biogas reactors. Renewable Energy. 123, 15-25.\
23. Wang, X., Yang, G., Feng, Y., Ren, G., Han, X., 2012. Optimizing feeding composition and carbon--nitrogen ratios for improved methane yield during anaerobic co-digestion of dairy, chicken manure and wheat straw. Bioresource Technology. 120, 78-83.\
24. Weiland, P., 2008. Wichtige Messdaten für den Prozessablauf und Stand der Technik in der Praxis. Gülzower Fachgespräche. 27, 17-31.\
25. Yadvika, Sreekrishnan, T., Kohli, S., Rana, V., 2004. Enhancement of biogas production from solid substrates using different techniques----a review. Bioresource technology. 95(1), 1-10.

# Appendix

Tab 6: Ampelsystem der BOKU Wien zur Einschätzung der gemessenen Parameter bezüglich der Arbeitsweise des Biogas-Reaktors (Laaber, 2012).

| Parameter    | Einheit   | Grün      | Gelb                 | Rot            |
|--------------|-----------|-----------|----------------------|----------------|
| CSB          | \[g/kg\]  | 40 - 90   | \< 40; 90 - 110      | \> 110         |
| TS           | \[% FM\]  | 4 - 8     | \< 4; 8 - 9          | \> 9           |
| oTS          | \[% FM\]  | 3 - 6     | \< 3; 6 - 7          | \> 7           |
| NH4+         | \[g/kg\]  | \< 5      | \> 5                 | \-             |
| Acetat       | \[g/L\]   | \< 1      | 1 - 3                | \> 3           |
| Propionat    | \[mg/L\]  | \< 250    | 250 - 1000           | \> 1000        |
| Butyrat      | \[mg/L\]  | \< 50     | 50 - 100             | \> 100         |
| Iso-Butyrat  | \[mg/L\]  | \< 60     | 60 - 200             | \> 200         |
| Valeriat     | \[mg/L\]  | \< 50     | 50 - 100             | \> 100         |
| Iso-Valeriat | \[mg/L\]  | \< 50     | 50 - 100             | \> 100         |
| VFA gesamt   | \[g/L\]   | \< 1.5    | 1.5 - 4.5            | \> 4.5         |
| EC           | \[mS/cm\] | 18 - 20   | \< 18; 20 - 60       | \> 60          |
| pH           | \-        | 7.5 - 8.1 | 7.1 - 7.5 \< 7.1;    | \> 8.1         |
| FOS/TAC      | \-        | 0.3 - 0.5 | 0.2 - 0.3; 0.5 - 0.6 | \< 0.2; \> 0.6 |
| C/N          | \-        | 20 - 30   | 15 - 20; 30 - 35     | \< 15; \> 35   |
